# Generated by Django 5.1.6 on 2025-03-16 01:05

from django.db import migrations, models

def migrate_shipped_data(apps, schema_editor):
    Order = apps.get_model('payment', 'Order')
    for order in Order.objects.all():
        order.shipped_temp = order.date_shipped is not None
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_shipping_address1_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_temp',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_shipped_data),
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipped_temp',
            new_name='shipped',
        ),
    ]


""" 
class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_date_shipped_alter_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
"""