# Generated by Django 5.1.6 on 2025-03-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_date_shipped_alter_order_shipped'),
        ('payment', '0005_order_date_shipped'),
    ]

    operations = [
    ]
